### ISSUE TITLE
Weather icons not displaying

### ISSUE THREAD

**Issue by cadie** [UCF/Today-Child-Theme#100]
**Describe the bug**
Weather icons are not being displayed in the nav: https://www.ucf.edu/news/
We've made some updates to the weather shortcode plugin recently, those might be related. https://github.com/UCF/UCF-Weather-Shortcode/releases/tag/v1.1.0

**Steps to Reproduce**

1. Go to https://www.ucf.edu/news/, the weather icon should be displayed in the top navigation to the left of the temperature

**Expected Behavior**
The weather icon should be displayed in the top navigation to the left of the temperature

**Your environment:**
 - Device: Macbook Pro
 - Browser & Version: Checked in Chrome & Firefox

**Comment by cjg89** [comment]
The custom layout for weather we have in this theme needs to be modified to be compatible with v1.1.0 of the UCF Weather Shortcode plugin by using `UCF_Weather_Common::get_weather_icon_svg()` instead of a custom `<span>` elem:

https://github.com/UCF/Today-Child-Theme/blob/master/includes/weather-functions.php#L31-L50

Example usage: https://github.com/UCF/UCF-Weather-Shortcode/blob/master/includes/ucf-weather-common.php#L125-L146

**Comment by cjg89** [comment]
Resolved in v1.0.11.
